server:
  servlet:
    context-path: /pay
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://192.168.1.77:3307/pay?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root1234
  redis:
    host: 192.168.1.77
    port: 6379
#    password: root@lee@redis

mybatis-plus:
  mapper-locations: classpath*:/com/lee/pay/config/mapper/xml/*.xml,classpath*:/com/lee/pay/utils/crud/mapper/xml/*.xml,classpath*:/com/lee/project/*.xml
  type-handlers-package: com.lee.pay.config
  global-config:
    db-config:
      logic-delete-field: flag    # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1       # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0   # 逻辑未删除值(默认为 0)


knife4j:
  enable: true
#  production: true
pay:
  swagger:
    enable: true



logging:
  level:
    com.lee: trace
